export const UPDATE_FIELDS = 'UPDATE_FIELDS';
export const RESET = 'RESET';
export const SUBMISSION_ERROR = 'SUBMISSION_ERROR';

export const STATUSES = {
    UNINITIALISED: 'UNINITIALISED',
    TOUCHED: 'TOUCHED',
    SUBMITTING: 'SUBMITTING',
};

export const ACTIONS = {
    FOCUSED: 'FOCUSED',
    BLURRED: 'BLURRED',
    CHANGED: 'CHANGED',
    SUBMIT: 'SUBMIT',
};